---
title: "BTW 2017"
author: "People"
date: "`r Sys.time()`"
output: 
  html_document: 
    self_contained: no
    toc: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path = "plots/")

source("init.R")

theme_set(tadaatoolbox::theme_tadaa())
```

## Distribution

```{r distribution}
btw17 %>%
  select(Laendernamen, `Wahlberechtigte (A)`, `Wähler (B)`, `Ungültige`:`Übrige`) %>%
  gather(key = Partei, value = Stimmen, CDU:`Übrige`) %>%
  group_by(Partei) %>%
  summarise(Prozent = sum(Stimmen) / sum(`Gültige`)) %>%
  mutate(Parteien = ifelse(Prozent <= .05, "Sonstige", Partei)) %>% 
  ggplot(aes(x = reorder(Parteien, -Prozent), y = Prozent, fill = Parteien)) +
  geom_col() +
  scale_y_continuous(labels = scales::percent) +
  scale_fill_manual(guide = FALSE, values = partei_colors) +
  labs(title = "Stimmanteil aller Parteien bundesweit", x = "Partei", y = "Stimmanteil")
```


### Distribution by State

```{r distribution_by_state}
btw_long %>%
  ggplot(aes(x = reorder(Parteien, Prozent), y = Prozent, fill = Parteien)) +
  geom_col() +
  scale_y_continuous(labels = scales::percent) +
  scale_fill_manual(breaks = names(partei_colors), values = partei_colors) +
  labs(title = "Stimmanteil aller Parteien >5% pro Bundesland") +
  facet_wrap(~Laendernamen) +
  coord_flip()
```


## Voter Turnout By State

```{r}
# create labels and color palette
labels <- paste0(
  laender$NAME_1, ": ", round(laender$Prozent * 100, 1), "%"
) %>% lapply(htmltools::HTML)

pal <- colorBin("YlGnBu", domain = laender$Prozent)

# create map
leaflet(laender) %>%
  addProviderTiles(providers$Esri) %>% # oder $Stamen.TonerLite
  addPolygons(weight = 2, color = "black", fillColor = ~pal(Prozent),
              dashArray = "4", fillOpacity = 0.5, label = labels,
              highlightOptions = highlightOptions(weight = 3, color = "#800000",
                                                  dashArray = "", fillOpacity = .8,
                                                  bringToFront = TRUE)) %>%
  addLegend(pal = pal, values = ~Prozent, opacity = 0.7, title = NULL, labels = "",
            position = "topright", labFormat = labelFormat(suffix = "%", digits = 2))
```
